### ISSUE TITLE
Complains about there not being an active session

### ISSUE THREAD

**Issue by patrickjquinn** [misterhat/mp3skull#2]
Their site has changed seemingly, if you throw error on search you get 

Error: No session found.
    at /Users/luke/yandex/node_modules/mp3skull/index.js:45:25
    at done (/Users/luke/mp/node_modules/mp3skull/node_modules/needle/lib/needle.js:355:7)

**Comment by patrickjquinn** [comment]
Are these changes currently live in the repo?

**Comment by Necktrox** [comment]
@patrickjquinn yes, the pull request has been merged
